name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: prod-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout (full history p/ métricas)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      # --- DEPLOY ---
      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      - name: Deploy
        id: deploy
        run: ./deploy.sh

      # --- NOTIFICAÇÃO PARA O SLEUTH ---
      # Este step só roda se todos os steps anteriores (incluindo o deploy) forem bem-sucedidos.
      - name: Notify Sleuth of Deployment
        if: success()
        uses: sleuth-io/action-sleuth@v2
        with:
          # A chave de API que você configurou nos Secrets do GitHub.
          api_key: ${{ secrets.SLEUTH_API_KEY }}

          # O nome do ambiente. DEVE ser idêntico ao nome do ambiente no Sleuth.
          environment: production

          # Opcional, mas altamente recomendado para métricas precisas.
          # Envia o hash do commit que foi implantado.
          revision: ${{ github.sha }}
